import { AgentStateType } from "../graph/state";
import { ceoLlm } from "../llm";
import { HumanMessage } from "@langchain/core/messages";

export async function supervisorNode(state: AgentStateType) {
  console.log("--- [CEO Agent] Reviewing Final Campaign Package ---");

  if (!state.campaignPayload || !state.campaignPayload.platforms) {
    throw new Error("No payload found for CEO to review.");
  }

  const prompt = `You are the CEO and Creative Director of the marketing agency.
Review the following complete campaign payload generated by your team:

${JSON.stringify(state.campaignPayload, null, 2)}

YOUR REVIEW CRITERIA:
1. Does this copy actually look human and professional, or does it scream "AI-generated marketing copy"?
2. Are there any banned AI words used (e.g. "fast-paced", "unlock", "dive into")?
3. Does the first sentence function as a true, curiosity-inducing pattern interrupt hook?
4. Is the tone appropriate and conversational?

If the copy feels robotic, generic, or fails the hook test, reject it and explain exactly what the Content Creator must fix.
Respond with exactly "APPROVED" if it passes all tests flawlessly, or a short paragraph explaining what needs fixing.`;

  const res = await ceoLlm.invoke([new HumanMessage(prompt)]);
  const reviewText = (res.content?.toString() || "").trim();

  console.log(`[CEO Review]: ${reviewText}`);

  // Prevent infinite loops by checking retry count
  const retryCount = state.messages?.filter(m => m.content.toString().includes("CEO Feedback")).length || 0;

  if (reviewText.includes("APPROVED") || retryCount >= 2) {
    if (retryCount >= 2 && !reviewText.includes("APPROVED")) {
      console.warn("CEO requested changes, but max retries reached. Approving.");
    }
    return {
      nextWorker: "FINISH",
      ceoVerdict: reviewText
    };
  } else {
    console.warn("CEO requested changes, pushing back to contentCreator.");
    return {
      nextWorker: "contentCreator",
      ceoVerdict: reviewText,
      messages: [new HumanMessage(`CEO Feedback: ${reviewText}`)]
    };
  }
}
