import { AgentStateType } from "../graph/state";
import { ceoLlm } from "../llm";
import { HumanMessage } from "@langchain/core/messages";

export async function supervisorNode(state: AgentStateType) {
  console.log("--- [CEO Agent] Reviewing Final Campaign Package ---");

  if (!state.campaignPayload || !state.campaignPayload.platforms) {
    throw new Error("No payload found for CEO to review.");
  }

  const prompt = `You are the CEO and Creative Director of the marketing agency.
Review the following complete campaign payload generated by your team:

${JSON.stringify(state.campaignPayload, null, 2)}

Does this campaign have a strong viral hook?
Are the captions engaging and accurate to the brand?
Are there visual images/urls ready?

Respond with exactly "APPROVED" if it is ready, or a short sentence on what needs fixing if it is completely broken.`;

  const res = await ceoLlm.invoke([new HumanMessage(prompt)]);
  const reviewText = (res.content?.toString() || "").trim();

  console.log(`[CEO Review]: ${reviewText}`);

  if (reviewText.includes("APPROVED")) {
    return {
      nextWorker: "FINISH",
      ceoVerdict: reviewText
    };
  } else {
    console.warn("CEO requested changes, but pushing to FINISH for preview.");
    return {
      nextWorker: "FINISH",
      ceoVerdict: reviewText,
      messages: [new HumanMessage(`CEO Feedback: ${reviewText}`)]
    };
  }
}
