/**
 * CENTRAL PLATFORM CAPABILITY REGISTRY
 * 
 * Defines official capabilities, limits, aspect ratios, fields, and publishing
 * capabilities for every social platform and content format.
 * Zero invented capabilities — strictly grounded in official platform behaviors.
 */

export type PlatformId = "instagram" | "facebook" | "pinterest" | "linkedin" | "tiktok" | "youtube" | "x";

export type FormatCategory = "organic" | "ads";

export type MediaType = "image" | "video" | "multi_image" | "carousel" | "document" | "text_only";

export type AspectRatio = "1:1" | "9:16" | "16:9" | "4:5" | "2:3" | "1.91:1";

export type PublishingMode = "api_direct" | "manual_export" | "ads_manager" | "eligibility_required";

export interface PlatformCapability {
  platform: PlatformId;
  format: string;               // e.g. "Feed", "Reel", "Carousel", "Pin", "Idea Pin", "Document"
  formatKey: string;            // normalized identifier: "instagram_carousel"
  label: string;                // Display title: "Feed Carousel", "Standard Pin"
  category: FormatCategory;
  mediaType: MediaType;
  defaultAspectRatio: AspectRatio;
  supportedAspectRatios: AspectRatio[];
  maxMedia: number;             // e.g. 10 for IG Carousel, 1 for Feed
  minMedia: number;
  
  // Content Field Capabilities
  supportsTitle: boolean;
  supportsDescription: boolean;
  supportsCaption: boolean;
  supportsFirstComment: boolean;
  supportsHashtags: boolean;
  supportsDestinationUrl: boolean;
  supportsBoard: boolean;
  supportsTaggedTopics: boolean;
  supportsAltText: boolean;
  supportsProductTags: boolean;
  supportsStorySettings: boolean;
  supportsPrivacySettings: boolean;
  supportsDuetStitch: boolean;
  supportsAIModifiedDisclosure: boolean;
  supportsMultiSlide: boolean;
  supportsDocumentExport: boolean;

  // Character Limits
  titleLimit?: number;
  captionLimit: number;
  descriptionLimit?: number;
  altTextLimit?: number;
  firstCommentLimit: number;
  hashtagLimit: number;

  // API Publishing Status
  publishingMode: PublishingMode;
  publishingNotice?: string;

  // AI Generation Capabilities
  supportsAIImage: boolean;
  supportsAIVideo: boolean;
  supportsAICarousel: boolean;
  supportsAIDocument: boolean;
}

export const PLATFORM_CAPABILITIES: Record<string, PlatformCapability> = {
  // ==========================================================================
  // INSTAGRAM
  // ==========================================================================
  "instagram:Feed": {
    platform: "instagram",
    format: "Feed",
    formatKey: "instagram_feed",
    label: "Feed Post",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "1:1",
    supportedAspectRatios: ["1:1", "4:5"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    // Instagram Graph API has no alt_text parameter on container creation —
    // alt text can only be set inside the Instagram app after publishing.
    supportsAltText: false,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 1000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "instagram:Carousel": {
    platform: "instagram",
    format: "Carousel",
    formatKey: "instagram_carousel",
    label: "Feed Carousel",
    category: "organic",
    mediaType: "carousel",
    defaultAspectRatio: "1:1",
    supportedAspectRatios: ["1:1", "4:5"],
    maxMedia: 10,
    minMedia: 2,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    // Instagram Graph API has no alt_text parameter on container creation.
    supportsAltText: false,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 1000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },
  "instagram:Reel": {
    platform: "instagram",
    format: "Reel",
    formatKey: "instagram_reel",
    label: "Instagram Reel",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 1000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "instagram:Story": {
    platform: "instagram",
    format: "Story",
    formatKey: "instagram_story",
    label: "Instagram Story",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    // STORIES containers in the Instagram Graph API do not accept a caption.
    // Text on stories must be burned into the image/video itself.
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: false,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: true,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 0,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // PINTEREST
  // ==========================================================================
  "pinterest:Pin": {
    platform: "pinterest",
    format: "Pin",
    formatKey: "pinterest_standard_pin",
    label: "Standard Pin",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "2:3",
    supportedAspectRatios: ["2:3", "9:16", "1:1"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: true,
    supportsBoard: true,
    supportsTaggedTopics: true,
    supportsAltText: true,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 500,
    altTextLimit: 500,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 20,
    publishingMode: "manual_export",
    publishingNotice: "Direct export / Pin creation ready",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "pinterest:Video Pin": {
    platform: "pinterest",
    format: "Video Pin",
    formatKey: "pinterest_video_pin",
    label: "Video Pin",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: true,
    supportsBoard: true,
    supportsTaggedTopics: true,
    supportsAltText: true,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 500,
    altTextLimit: 500,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 20,
    publishingMode: "manual_export",
    publishingNotice: "Direct export / Video Pin ready",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "pinterest:Idea Pin": {
    platform: "pinterest",
    format: "Idea Pin",
    formatKey: "pinterest_idea_pin",
    label: "Idea Pin (Multi-Page)",
    category: "organic",
    mediaType: "carousel",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 10,
    minMedia: 2,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: true,
    supportsBoard: true,
    supportsTaggedTopics: true,
    supportsAltText: true,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 500,
    altTextLimit: 500,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 20,
    publishingMode: "manual_export",
    publishingNotice: "Multi-page storyboard export ready",
    supportsAIImage: true,
    supportsAIVideo: true,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },
  "pinterest:Carousel": {
    platform: "pinterest",
    format: "Carousel",
    formatKey: "pinterest_carousel",
    label: "Carousel Pin (2-5 Cards)",
    category: "organic",
    mediaType: "carousel",
    defaultAspectRatio: "2:3",
    supportedAspectRatios: ["2:3", "1:1"],
    maxMedia: 5,
    minMedia: 2,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: true,
    supportsBoard: true,
    supportsTaggedTopics: true,
    supportsAltText: true,
    supportsProductTags: true,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 500,
    altTextLimit: 500,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 20,
    publishingMode: "manual_export",
    publishingNotice: "Pinterest Carousel officially supports 2-5 cards — manual export workflow",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // LINKEDIN
  // ==========================================================================
  "linkedin:Post": {
    platform: "linkedin",
    format: "Post",
    formatKey: "linkedin_post",
    label: "Post (Single Image / Text)",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "1.91:1",
    supportedAspectRatios: ["1.91:1", "1:1", "4:5"],
    maxMedia: 1,
    minMedia: 0,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: true,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 3000,
    firstCommentLimit: 1250,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "linkedin:Multi-Image": {
    platform: "linkedin",
    format: "Multi-Image",
    formatKey: "linkedin_multi_image",
    label: "Multiple Photos (Organic)",
    category: "organic",
    mediaType: "multi_image",
    defaultAspectRatio: "1:1",
    supportedAspectRatios: ["1:1", "1.91:1", "4:5"],
    maxMedia: 9,
    minMedia: 2,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: true,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    captionLimit: 3000,
    firstCommentLimit: 1250,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },
  "linkedin:Document": {
    platform: "linkedin",
    format: "Document",
    formatKey: "linkedin_document",
    label: "Document Post (PDF Carousel)",
    category: "organic",
    mediaType: "document",
    defaultAspectRatio: "4:5",
    supportedAspectRatios: ["4:5", "1:1"],
    maxMedia: 15,
    minMedia: 2,
    supportsTitle: true,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: true,
    supportsDocumentExport: true,
    titleLimit: 100,
    captionLimit: 3000,
    firstCommentLimit: 1250,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    publishingNotice: "Multi-slide PDF ready for direct publishing & export",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: true,
  },
  "linkedin:Video": {
    platform: "linkedin",
    format: "Video",
    formatKey: "linkedin_video",
    label: "Video Post",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16", "16:9", "1:1"],
    maxMedia: 1,
    minMedia: 1,
    // LinkedIn video uploads support a media title + description (alt text)
    // via the digitalmedia asset metadata on /v2/ugcPosts.
    supportsTitle: true,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    titleLimit: 200,
    captionLimit: 3000,
    firstCommentLimit: 1250,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // FACEBOOK
  // ==========================================================================
  "facebook:Feed": {
    platform: "facebook",
    format: "Feed",
    formatKey: "facebook_feed",
    label: "Feed Post",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "1:1",
    supportedAspectRatios: ["1:1", "16:9", "4:5"],
    maxMedia: 1,
    minMedia: 0,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    // Facebook Graph API /photos and /feed have no alt_text parameter on publish.
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 63206,
    firstCommentLimit: 8000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "facebook:Multiple Photos": {
    platform: "facebook",
    format: "Multiple Photos",
    formatKey: "facebook_multi_photo",
    label: "Multiple Photos & Videos",
    category: "organic",
    mediaType: "multi_image",
    defaultAspectRatio: "1:1",
    supportedAspectRatios: ["1:1", "16:9", "4:5"],
    maxMedia: 10,
    minMedia: 2,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    // Facebook Graph API has no alt_text parameter on publish.
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    captionLimit: 63206,
    firstCommentLimit: 8000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },
  "facebook:Reel": {
    platform: "facebook",
    format: "Reel",
    formatKey: "facebook_reel",
    label: "Facebook Reel",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 8000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "facebook:Story": {
    platform: "facebook",
    format: "Story",
    formatKey: "facebook_story",
    label: "Facebook Story",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: false,
    supportsHashtags: false,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: true,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 500,
    firstCommentLimit: 0,
    hashtagLimit: 0,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // TIKTOK
  // ==========================================================================
  "tiktok:Video": {
    platform: "tiktok",
    format: "Video",
    formatKey: "tiktok_video",
    label: "TikTok Video",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: true,
    supportsDuetStitch: true,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 0,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "tiktok:Photo": {
    platform: "tiktok",
    format: "Photo",
    formatKey: "tiktok_photo",
    label: "Photo Mode (Carousel)",
    category: "organic",
    mediaType: "carousel",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16", "1:1"],
    // TikTok Content Posting API accepts 1-35 photos per photo post.
    maxMedia: 35,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: true,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    // Photo posts: title max 90 UTF-16 runes, description max 4000 (official docs).
    titleLimit: 90,
    descriptionLimit: 4000,
    captionLimit: 4000,
    firstCommentLimit: 0,
    hashtagLimit: 10,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // YOUTUBE
  // ==========================================================================
  "youtube:Shorts": {
    platform: "youtube",
    format: "Shorts",
    formatKey: "youtube_shorts",
    label: "YouTube Shorts",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "9:16",
    supportedAspectRatios: ["9:16"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: true,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 5000,
    captionLimit: 5000,
    firstCommentLimit: 5000,
    hashtagLimit: 15,
    publishingMode: "api_direct",
    supportsAIImage: false,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "youtube:Video": {
    platform: "youtube",
    format: "Video",
    formatKey: "youtube_video",
    label: "Long-form Video",
    category: "organic",
    mediaType: "video",
    defaultAspectRatio: "16:9",
    supportedAspectRatios: ["16:9"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: true,
    supportsDescription: true,
    supportsCaption: false,
    supportsFirstComment: false,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: false,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: true,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: true,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    titleLimit: 100,
    descriptionLimit: 5000,
    captionLimit: 5000,
    firstCommentLimit: 5000,
    hashtagLimit: 15,
    publishingMode: "api_direct",
    supportsAIImage: true, // For Thumbnail
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },

  // ==========================================================================
  // X (TWITTER)
  // ==========================================================================
  "x:Post": {
    platform: "x",
    format: "Post",
    formatKey: "x_post",
    label: "Post (Single / Media)",
    category: "organic",
    mediaType: "image",
    defaultAspectRatio: "16:9",
    supportedAspectRatios: ["16:9", "1:1"],
    maxMedia: 4,
    minMedia: 0,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: true,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 280,
    altTextLimit: 1000,
    firstCommentLimit: 280,
    hashtagLimit: 5,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: true,
    supportsAICarousel: false,
    supportsAIDocument: false,
  },
  "x:Thread": {
    platform: "x",
    format: "Thread",
    formatKey: "x_thread",
    label: "Thread (Multi-Tweet)",
    category: "organic",
    mediaType: "carousel",
    defaultAspectRatio: "16:9",
    supportedAspectRatios: ["16:9", "1:1"],
    maxMedia: 10,
    minMedia: 2,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: true,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: true,
    supportsDocumentExport: false,
    captionLimit: 280,
    firstCommentLimit: 280,
    hashtagLimit: 5,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: true,
    supportsAIDocument: false,
  },
};

/**
 * Resolver function to get capability definition
 */
export function getPlatformCapability(platformId: string, formatName: string): PlatformCapability {
  const normPlatform = platformId.toLowerCase().trim();
  const directKey = `${normPlatform}:${formatName}`;

  if (PLATFORM_CAPABILITIES[directKey]) {
    return PLATFORM_CAPABILITIES[directKey];
  }

  // Fallback matching by format name variations
  const matchedKey = Object.keys(PLATFORM_CAPABILITIES).find(k => {
    const [p, f] = k.split(":");
    return p === normPlatform && (
      f.toLowerCase() === formatName.toLowerCase() ||
      formatName.toLowerCase().includes(f.toLowerCase()) ||
      f.toLowerCase().includes(formatName.toLowerCase())
    );
  });

  if (matchedKey && PLATFORM_CAPABILITIES[matchedKey]) {
    return PLATFORM_CAPABILITIES[matchedKey];
  }

  // Default fallback
  return {
    platform: normPlatform as PlatformId,
    format: formatName,
    formatKey: `${normPlatform}_${formatName.toLowerCase().replace(/\s+/g, "_")}`,
    label: `${formatName}`,
    category: "organic",
    mediaType: formatName.toLowerCase().includes("video") || formatName.toLowerCase().includes("reel") || formatName.toLowerCase().includes("short") ? "video" : formatName.toLowerCase().includes("carousel") || formatName.toLowerCase().includes("idea") ? "carousel" : "image",
    defaultAspectRatio: formatName.toLowerCase().includes("reel") || formatName.toLowerCase().includes("short") || formatName.toLowerCase().includes("story") ? "9:16" : "1:1",
    supportedAspectRatios: ["1:1", "9:16", "16:9"],
    maxMedia: 1,
    minMedia: 1,
    supportsTitle: false,
    supportsDescription: false,
    supportsCaption: true,
    supportsFirstComment: true,
    supportsHashtags: true,
    supportsDestinationUrl: false,
    supportsBoard: false,
    supportsTaggedTopics: false,
    supportsAltText: true,
    supportsProductTags: false,
    supportsStorySettings: false,
    supportsPrivacySettings: false,
    supportsDuetStitch: false,
    supportsAIModifiedDisclosure: false,
    supportsMultiSlide: false,
    supportsDocumentExport: false,
    captionLimit: 2200,
    firstCommentLimit: 1000,
    hashtagLimit: 30,
    publishingMode: "api_direct",
    supportsAIImage: true,
    supportsAIVideo: false,
    supportsAICarousel: false,
    supportsAIDocument: false,
  };
}
