import type { Metadata } from "next";
import { PolicyPage } from "@/components/marketing/policy-page";

export const metadata: Metadata = {
  title: "Acceptable Use Policy — PostloomAI",
  description: "The rules for using PostloomAI: prohibited content, spam, automation limits, API usage and account suspension terms.",
};

export default function AcceptableUsePage() {
  return (
    <PolicyPage
      title="Acceptable Use Policy"
      updated="August 30, 2026"
      intro="This policy sets the rules for using PostloomAI and our APIs. It exists to keep the platform safe, reliable and trustworthy for everyone. It applies to all users worldwide."
      sections={[
        {
          heading: "1. You May Not Use PostloomAI To",
          list: [
            "Publish spam, misleading claims, or content designed to manipulate platform algorithms or users.",
            "Create or distribute hate speech, harassment, violence, or content that exploits or harms minors.",
            "Generate or spread malware, phishing pages, scams or fraudulent schemes.",
            "Impersonate people or brands, or publish content you don't have the rights to use.",
            "Violate the terms of connected platforms (Instagram, TikTok, LinkedIn, Facebook, YouTube, Pinterest) or applicable laws in your country.",
          ],
        },
        {
          heading: "2. Fair Use of Automation & APIs",
          paragraphs: [
            "Our AI agents and API are built for legitimate marketing automation. To keep the service fast for everyone, we apply fair-use limits: rate limits per plan, protection against abuse and monitoring for abnormal usage patterns.",
            "You may not resell access to your account, share API keys publicly, circumvent rate limits, or use the API to build a competing AI marketing product without a written partnership agreement.",
          ],
        },
        {
          heading: "3. Human Review Requirement",
          paragraphs: [
            "AI-generated content must be reviewed by a human before publishing where platform policies or local law require it. You are responsible for the content you publish through PostloomAI, even when it was generated by our AI.",
          ],
        },
        {
          heading: "4. Enforcement",
          paragraphs: [
            "We may warn, limit features, suspend or terminate accounts that violate this policy. Serious violations (illegal content, fraud, security abuse) may result in immediate termination without refund, and we may report unlawful activity to the relevant authorities.",
          ],
        },
        {
          heading: "5. Reporting Abuse",
          paragraphs: [
            "If you believe an account is violating this policy, contact us through the Contact page. We investigate every report and take action where needed.",
          ],
        },
      ]}
    />
  );
}
