"use client";

import React from "react";
import { Loader2, RefreshCw, Zap, Briefcase, Hash, Square } from "lucide-react";
import { cancelAIAction } from "@/lib/aiActionEvents";

export type CaptionRefineAction = "regenerate" | "boost-hook" | "executive-tone" | "add-hashtags";

interface CaptionRefineActionsProps {
  /** `${platform}-${format}` key used to route the stop signal */
  formatKey: string;
  /** The visible field text — bar is hidden until it has content */
  caption: string;
  onRefine: (action: CaptionRefineAction) => void;
  isRefining: boolean;
  refiningAction: string | null;
}

const ACTIONS: { key: CaptionRefineAction; label: string; icon: React.ReactNode }[] = [
  { key: "regenerate", label: "Rewrite Caption", icon: <RefreshCw className="h-3 w-3" /> },
  { key: "boost-hook", label: "Boost Hook", icon: <Zap className="h-3 w-3" /> },
  { key: "executive-tone", label: "Executive Tone", icon: <Briefcase className="h-3 w-3" /> },
  { key: "add-hashtags", label: "Add Hashtags", icon: <Hash className="h-3 w-3" /> },
];

/**
 * Quick caption refinement bar — appears ONLY once a caption/description
 * actually exists (typed by the user or generated by an AI button).
 * Each action is stoppable: the in-flight action turns into a red Stop pill.
 */
export default function CaptionRefineActions({
  formatKey,
  caption,
  onRefine,
  isRefining,
  refiningAction,
}: CaptionRefineActionsProps) {
  if (!caption || !caption.trim()) return null;

  return (
    <div className="flex items-center gap-1.5 flex-wrap pt-0.5">
      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">AI Caption Tools:</span>
      {ACTIONS.map(({ key, label, icon }) => {
        const isActive = isRefining && refiningAction === key;
        const isDisabled = isRefining && refiningAction !== key;
        return (
          <button
            key={key}
            type="button"
            disabled={isDisabled}
            onClick={() => {
              if (isActive) {
                cancelAIAction("refine", formatKey);
                return;
              }
              onRefine(key);
            }}
            title={isActive ? `Stop: ${label}` : label}
            className={`text-[10px] font-bold flex items-center gap-1 px-2 py-1 rounded-md transition-colors ${
              isActive
                ? "bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40"
                : isDisabled
                ? "bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500 cursor-not-allowed"
                : "bg-violet-50 dark:bg-violet-950/40 text-violet-600 dark:text-violet-400 hover:bg-violet-100 dark:hover:bg-violet-900/40"
            }`}
          >
            {isActive ? (
              <>
                <Square className="h-3 w-3 fill-current" />
                <Loader2 className="h-3 w-3 animate-spin" />
                <span>Stop</span>
              </>
            ) : (
              <>
                {icon}
                <span>{label}</span>
              </>
            )}
          </button>
        );
      })}
    </div>
  );
}
