// ============================================================================
// CONTROLLER MODEL REGISTRY
//
// The chat used to run on exactly one brain. It still ships with one — Gemini
// 3.1 Pro Preview — but the list is now a catalogue an admin can extend from the
// dashboard: a custom model row (see `AiModel` in the schema) that is enabled for
// chat appears in the picker, carries its own per-turn credit price, and can be
// restricted to a minimum plan.
//
// Two halves, deliberately:
//
//   The built-in default and the pure helpers below are client-safe (no prisma,
//   no env beyond NEXT_PUBLIC_*), so the composer and the settings panel can
//   import them. Their catalogue is whatever `setChatModelCatalog` last pushed —
//   on the server that is the runtime config; in the browser the list arrives
//   from /api/chat/settings and is passed down as props.
//
//   `setChatModelCatalog` is the server hook `runtimeConfig` calls after every
//   reload, so a model added in the back office is selectable on the next turn
//   without a deploy.
//
// It never renders media itself. Images and video have their own dedicated
// models, resolved server-side from MODELS.VISUALIZER / MODELS.VIDEO in llm.ts.
// ============================================================================

import type { PlanTier } from "@/lib/billing/plans";

/** The shipped controller model id. Override with NEXT_PUBLIC_MODEL_CHAT_CONTROLLER. */
export const CONTROLLER_MODEL_ID =
  process.env.NEXT_PUBLIC_MODEL_CHAT_CONTROLLER?.trim() || "gemini-3.1-pro-preview";

export interface ChatModelRate {
  inputPerMTok: number;
  outputPerMTok: number;
  cachedPerMTok?: number;
  perImage?: number;
  perVideoSecond?: number;
}

export interface ChatModelInfo {
  id: string;
  label: string;
  /** One-line pitch shown next to the model. */
  blurb: string;
  /** Emits `thought` parts, so live thinking works. */
  supportsThinking: boolean;
  /** Reliable with native function declarations (needed for tool use). */
  supportsTools: boolean;
  supportsVision: boolean;
  /** Shown as the recommended default. */
  recommended?: boolean;
  tier: "frontier" | "fast" | "legacy";
  /** False hides it from the picker while keeping it resolvable for old sessions. */
  enabledForChat?: boolean;
  /** Credits one chat turn costs on this model. Undefined = the catalogue's flat price. */
  chatCredits?: number;
  /** Cheapest plan that may pick it. Undefined = any plan with chat. */
  minPlan?: PlanTier;
  /** "text" | "image" | "video" | "embed" — only text models are pickable in chat. */
  kind?: string;
  /** True for rows the admin created, so the screen can say where it came from. */
  custom?: boolean;
  /**
   * Which model company serves it — a `ProviderSpec.id` from the provider
   * registry. Undefined means the built-in Google path. Safe to send to the
   * browser: it is a vendor label, never a credential or an endpoint.
   */
  provider?: string;
  /** Context size in tokens, for display next to the model. */
  contextWindow?: number;
  /** List price, for the admin cost view and the meter. */
  rate?: ChatModelRate;
  sortOrder?: number;
}

/** "gemini-3.1-pro-preview" → "Gemini 3.1 Pro Preview", for an overridden id. */
export function prettyModelLabel(id: string): string {
  return id
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => (/^[a-z]/.test(part) ? part[0].toUpperCase() + part.slice(1) : part))
    .join(" ");
}

export const BUILT_IN_CHAT_MODEL: ChatModelInfo = {
  id: CONTROLLER_MODEL_ID,
  label:
    CONTROLLER_MODEL_ID === "gemini-3.1-pro-preview"
      ? "Gemini 3.1 Pro (Preview)"
      : prettyModelLabel(CONTROLLER_MODEL_ID),
  blurb:
    "Plans the work, reasons out loud and drives every tool in the product. " +
    "Images and video are generated by their own models when it calls them.",
  supportsThinking: true,
  supportsTools: true,
  supportsVision: true,
  recommended: true,
  tier: "frontier",
  enabledForChat: true,
  kind: "text",
  sortOrder: 0,
};

let catalog: ChatModelInfo[] = [BUILT_IN_CHAT_MODEL];
let defaultId: string = CONTROLLER_MODEL_ID;

/**
 * Replaces the live catalogue. Custom rows override a built-in row with the same
 * id; the default is the admin's CHAT_CONTROLLER role pick, else the row marked
 * `recommended`, else the shipped model. Called by the runtime config on the
 * server and by the chat workbench in the browser.
 */
export function setChatModelCatalog(custom: ChatModelInfo[], preferredDefaultId?: string | null): void {
  const byId = new Map<string, ChatModelInfo>();
  byId.set(BUILT_IN_CHAT_MODEL.id, BUILT_IN_CHAT_MODEL);
  for (const model of custom || []) {
    if (!model?.id) continue;
    const base = byId.get(model.id);
    byId.set(model.id, base ? { ...base, ...model, recommended: model.recommended ?? base.recommended } : model);
  }

  const list = [...byId.values()].sort(
    (a, b) => (a.sortOrder ?? 100) - (b.sortOrder ?? 100) || a.label.localeCompare(b.label)
  );

  // A default has to be selectable. An admin can pin CHAT_CONTROLLER to a row and
  // later disable it for chat (or switch it to an image model); honouring that
  // pick would make `getDefaultChatModelId()` name a model the picker never shows
  // and `isKnownChatModel` rejects, so every new chat would start on a model it
  // is not allowed to use.
  const preferredRow = preferredDefaultId ? byId.get(preferredDefaultId) : undefined;
  const preferred = preferredRow && isPickable(preferredRow) ? preferredRow.id : null;
  const flagged = list.find((m) => m.recommended && m.custom && isPickable(m))?.id ?? null;
  const firstPickable = list.find(isPickable)?.id ?? null;
  const next = preferred ?? flagged ?? firstPickable ?? CONTROLLER_MODEL_ID;

  catalog = list.map((m) => ({ ...m, recommended: m.id === next }));
  defaultId = next;
}

function isPickable(model: ChatModelInfo): boolean {
  return model.enabledForChat !== false && (model.kind ?? "text") === "text";
}

/** Every model the picker may show. */
export function listChatModels(): ChatModelInfo[] {
  return catalog.filter(isPickable);
}

/** Every model the catalogue knows, including disabled ones (for old sessions). */
export function allChatModels(): ChatModelInfo[] {
  return catalog;
}

export function getDefaultChatModelId(): string {
  return defaultId;
}

/** Kept for existing imports; prefer `getDefaultChatModelId()` for the live value. */
export const DEFAULT_CHAT_MODEL = CONTROLLER_MODEL_ID;

export function getChatModel(id: string | null | undefined): ChatModelInfo {
  return catalog.find((m) => m.id === id) || catalog.find((m) => m.id === defaultId) || BUILT_IN_CHAT_MODEL;
}

/** True when a user may select this id right now. */
export function isKnownChatModel(id: string | null | undefined): boolean {
  return !!id && catalog.some((m) => m.id === id && isPickable(m));
}

/**
 * Whether this plan may use this model. A model with no `minPlan` is open to any
 * plan that has chat at all; the plan gate for chat itself is checked elsewhere.
 */
export function planMayUseModel(model: ChatModelInfo, plan: PlanTier | string | null | undefined, rank: (tier: PlanTier) => number): boolean {
  if (!model.minPlan) return true;
  if (!plan) return false;
  return rank(plan as PlanTier) >= rank(model.minPlan);
}

/**
 * What to show as the model that served a turn. The provider may fall back to
 * another model when the region is out of capacity, and saying "Gemini 3.1 Pro"
 * when something else answered would be a lie — so an unknown id is shown as-is.
 */
export function chatModelLabel(id: string | null | undefined): string {
  if (!id) return getChatModel(defaultId).label;
  return catalog.find((m) => m.id === id)?.label || id;
}

/** The picker list with only what the browser needs. */
export function serializeChatModels(): ChatModelInfo[] {
  return listChatModels().map((m) => ({
    id: m.id,
    label: m.label,
    blurb: m.blurb,
    supportsThinking: m.supportsThinking,
    supportsTools: m.supportsTools,
    supportsVision: m.supportsVision,
    recommended: m.recommended,
    tier: m.tier,
    enabledForChat: true,
    chatCredits: m.chatCredits,
    minPlan: m.minPlan,
    kind: m.kind ?? "text",
    custom: m.custom,
    // Vendor label and context size: the settings panel shows both, and neither
    // is a credential or an endpoint.
    provider: m.provider,
    contextWindow: m.contextWindow,
    sortOrder: m.sortOrder,
  }));
}
