// ============================================================================
// CONTROLLER MODEL REGISTRY
//
// The controller runs on exactly one brain: Gemini 3.1 Pro Preview. It is the
// only model here that reasons, plans and drives tools across a whole task, so
// there is nothing to choose between — the picker states which brain is running
// rather than offering weaker ones.
//
// It never renders media itself. Images and video have their own dedicated
// models, resolved server-side from the env-driven map in src/lib/agents/llm.ts
// (MODELS.VISUALIZER / MODELS.VIDEO) and reached through the generate_image and
// generate_video tools: the controller decides what to make, those models make
// it. The id below is the single place the chat model string is written in the
// whole app, and it is env-overridable so swapping brains never needs a code
// change.
// ============================================================================

/** The one controller model id. Override with NEXT_PUBLIC_MODEL_CHAT_CONTROLLER. */
export const CONTROLLER_MODEL_ID =
  process.env.NEXT_PUBLIC_MODEL_CHAT_CONTROLLER?.trim() || "gemini-3.1-pro-preview";

export interface ChatModelInfo {
  id: string;
  label: string;
  /** One-line pitch shown next to the model. */
  blurb: string;
  /** Emits `thought` parts, so live thinking works. */
  supportsThinking: boolean;
  /** Reliable with native function declarations (needed for tool use). */
  supportsTools: boolean;
  supportsVision: boolean;
  /** Shown as the recommended default. */
  recommended?: boolean;
  tier: "frontier" | "fast" | "legacy";
}

/** "gemini-3.1-pro-preview" → "Gemini 3.1 Pro Preview", for an overridden id. */
function prettyLabel(id: string): string {
  return id
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => (/^[a-z]/.test(part) ? part[0].toUpperCase() + part.slice(1) : part))
    .join(" ");
}

export const DEFAULT_CHAT_MODEL = CONTROLLER_MODEL_ID;

export const CHAT_MODELS: ChatModelInfo[] = [
  {
    id: CONTROLLER_MODEL_ID,
    label:
      CONTROLLER_MODEL_ID === "gemini-3.1-pro-preview"
        ? "Gemini 3.1 Pro (Preview)"
        : prettyLabel(CONTROLLER_MODEL_ID),
    blurb:
      "Plans the work, reasons out loud and drives every tool in the product. " +
      "Images and video are generated by their own models when it calls them.",
    supportsThinking: true,
    supportsTools: true,
    supportsVision: true,
    recommended: true,
    tier: "frontier",
  },
];

export function getChatModel(id: string | null | undefined): ChatModelInfo {
  return CHAT_MODELS.find((m) => m.id === id) || CHAT_MODELS[0];
}

export function isKnownChatModel(id: string | null | undefined): boolean {
  return !!id && CHAT_MODELS.some((m) => m.id === id);
}

/**
 * What to show as the model that served a turn. The provider may fall back to
 * another model when the region is out of capacity, and saying "Gemini 3.1 Pro"
 * when something else answered would be a lie — so an unknown id is shown as-is.
 */
export function chatModelLabel(id: string | null | undefined): string {
  if (!id) return CHAT_MODELS[0].label;
  return CHAT_MODELS.find((m) => m.id === id)?.label || id;
}
